---
- name: Sequence to take a new snapshot
  when:
    - take_snapshot is defined
    - take_snapshot == "True"
  block:
    - name: Wait until VMware tools available
      community.vmware.vmware_guest_tools_wait:
        hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
        username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
        password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"
        validate_certs: "{{ validate_certs | default(false) }}"
        folder: "{{ vm_folder | default('vm') }}"
        name: "{{ vm_name }}.{{ domain }}"

    - name: Ensure power state of VM
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
        username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
        password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"
        validate_certs: "{{ validate_certs | default(false) }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder | default('vm') }}"
        name: "{{ vm_name }}.{{ domain }}"
      register: ensure_power_state_result

    - name: Shutdown vm
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
        username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
        password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"
        validate_certs: "{{ validate_certs | default(false) }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder | default('vm') }}"
        name: "{{ vm_name }}.{{ domain }}"
        state: shutdownguest

    - name: Wait until vm power stop
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
        username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
        password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"
        validate_certs: "{{ validate_certs | default(false) }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder | default('vm') }}"
        name: "{{ vm_name }}.{{ domain }}"
      register: shutdown_vm_result
      retries: 60
      delay: 10
      until: shutdown_vm_result.instance.hw_power_status == "poweredOff"

    - name: Take a new snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
        username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
        password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"
        validate_certs: "{{ validate_certs | default(false) }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder | default('vm') }}"
        name: "{{ vm_name }}.{{ domain }}"
        state: present
        snapshot_name: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

    - name: Start vm
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
        username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
        password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"
        validate_certs: "{{ validate_certs | default(false) }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder | default('vm') }}"
        name: "{{ vm_name }}.{{ domain }}"
        state: poweredon

    - name: Wait until starting vmware tools
      community.vmware.vmware_guest_tools_info:
        hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
        username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
        password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"
        validate_certs: "{{ validate_certs | default(false) }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}.{{ domain }}"
      register: get_vm_tools_info_result
      until: get_vm_tools_info_result.vmtools_info.vm_tools_running_status == "guestToolsRunning"
      retries: 300
      delay: 10
